
# General settings

# Update Interval / Timespan between synchronizations of Worldguard with Bluemap. (default: 10 seconds / 200 ticks)
# Keep this number bigger than the amount of worlds loaded in Bluemap, as the plugin will spread the workload over multiple ticks (1 per loaded world).
# Markers are created in an async thread
update-interval: 200

# Markerset display name in the sidebar of Bluemap's webinterface
markerset-name: "WorldGuard Regions"

# Region settings

# Render all regions by default (Setting the "render-on-bluemap" flag on individual regions overwrites this setting)
render-flag-default: true

# Default height to render regions at (if not defined otherwise using the "bluemap-render-height" flag of a region)
render-height: 64

# Default region color (can be configured per region using "bluemap-color". Use a hexadecimal RGBA color code (Format: AARRGGBB).)
region-color: "960087ff"

# Default outline color (can be configured per region using "bluemap-color-outline". Use a hexadecimal RGB color code.)
outline-color: "0060ff"

# Use html preset instead of region id or bluemap-display flag (if defined)
use-html: true

# Preset of the html formatted text to be displayed when clicking on a region in Bluemap.
# Html and CSS are supported.
# Look up YAML multiline string syntax if you want to use a custom preset.
#
# IMPORTANT: This Plugin will sanitize the generated html string in the future, but as long as this disclaimer is present,
# do NOT allow for any user input by people you don't trust or make sure you prevent users from using html tags (e.g. in their region names) in any other way!
#
# The default setting will:
# - Display the name of the region in the color of its bluemap-color-outline tag
# - Display the area and volume of the region
# - Display all (or up to 10) owners and members as two lists next to each other
#
# Variables:
# ${name}: The name / Worldguard id of the region
# ${owners}: a list of all player owner names. Max size of 10.
# ${members}: a list of all player members. Max size of 10.
# ${size:2d} / ${size:3d}: the size of the region in square or cubic blocks
# ${flag:flagname}: the value of the given worldguard flag
html-preset: |-
  <h2 style="color:#${flag:bluemap-color-outline};text-align:center;margin-block-end:0.3em">
  ${name}
  </h2>
  <p style="text-align:center">
  Area: ${size:2d}<br>Volume: ${size:3d}
  </p>
  <div style="display:flex">
  <div style="flex:50%;padding:10px">
  <h3 style="margin-block-start:0.3em;margin-block-end:0.3em">
  Owners
  </h3>
  <p>
  <span>
  ${owners}
  </span>
  </p>
  </div>
  <div style="flex:50%;padding:10px">
  <h3 style="margin-block-start:0.3em;margin-block-end:0.3em">
  Members
  </h3>
  <p>
  <span>
  ${members}
  </span>
  </p>
  </div>
  </p>





# Other values configurable only using Worldguard flags:

# flag name               description
#-----------------------------------------------------------------------------------------------------
# bluemap-display         Sets the text to be displayed when clicking on the region