
# General settings

# Update Interval / Timespan between synchronizations of Worldguard with Bluemap. (default: 10 seconds / 200 ticks)
# Keep this number bigger than the amount of worlds loaded in Bluemap, as the plugin will spread the workload over multiple ticks (1 per loaded world).
# Markers are created in an async thread
update-interval: 200

# Markerset display name in the sidebar of Bluemap's webinterface
markerset-name: "WorldGuard Regions"

# Region settings

# Render all regions by default (Setting the "render-on-bluemap" flag on individual regions overwrites this setting)
render-flag-default: true

# Default height to render regions at (if not defined otherwise using the "bluemap-render-height" flag of a region)
render-height: 64

# Default region color (can be configured per region using "bluemap-color". Use a hexadecimal RGBA color code (Format: AARRGGBB).)
region-color: "960087ff"

# Default outline color (can be configured per region using "bluemap-color-outline". Use a hexadecimal RGB color code.)
outline-color: "0060ff"





# Other values configurable only using Worldguard flags:

# flag name               description
#-----------------------------------------------------------------------------------------------------
# bluemap-display         Sets the text to be displayed when clicking on the region